los-controller/Controllers/CustomerCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using los_controller.Models;

namespace los_controller.Controllers
{
    
    public class CustomerCategoryController : Controller
    {
        //
        // GET: /CustomerCategory/
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetCustCatTree()
        {
            List<TreeModel> treelist = new List<TreeModel> {
                new TreeModel { Id="Ca1", Name="Cattest2" , ParentId="Ca"},
                new TreeModel { Id="Ca", Name = "Cattest1", ParentId=  null },
                new TreeModel { Id="Ca2", Name="Cattest3" , ParentId= "Ca"}
            };
            return Json(treelist,JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public PartialViewResult GetCustCatDetail(string CustCatID)
        {
            return PartialView("CustomerCategoryDetail");
        }

        [HttpGet]
        public PartialViewResult NewCustomerCatgory()
        {
            CustomerCategoryViewModel model = new CustomerCategoryViewModel();
            model.AuditOperation = "I";
            model.TranAction = "I";
            return PartialView("CustomerCategoryEditView", model);
        }

        [HttpGet]
        public PartialViewResult EditCustomerCategory(string CustCatID)
        {
            CustomerCategory model = new CustomerCategory();
            model.AuditOperation = "U";
            model.TranAction = "I";
            return PartialView("CustomerCategoryEditView",model);
        }

        public JsonResult SaveCustomerCategory(CustomerCategoryViewModel model)
        {
            
            return Json("True");
        }

        public JsonResult DeleteCustomerCategory(string CustCatID)
        {
            return Json("True");
        }

        public ViewResult GetAudList()
        {
            return View();
        }

        public PartialViewResult GetAudDetail(string CustcatAudId)
        {
            return PartialView("");
        }

        public JsonResult Approve(string CustcatAudId)
        {
            return Json("");
        }

        public JsonResult Reject(string CustcatAudId)
        {
            return Json("");
        }
	}
}

los-controller/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using los_controller.Models;
using los_controller.Infrastructure.BusinessLogic;
using RestSharp;
using System.Net;
using los_controller.Infrastructure.Utility;
using System.Web.Script.Serialization;
using los_controller.Validation;
using AutoMapper;
using los_controller.Utility;
using DevExpress.Web.Mvc;

namespace los_controller.Controllers
{
    [Authorize]
    public class ProductController : BaseController
    {


        //
        // GET: /Product/
        public ViewResult Index()
        {
            return View();
        }

        [AcceptVerbs(HttpVerbs.Get)]
        public JsonResult GetProductTree()
        {
            List<TreeModel> listresult = ProductRepository.GetProductTree();
            return Json(listresult, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public PartialViewResult GetProductDetail(string productId)
        {
            ViewData["ButtonBar"] = ProductRepository.GetPermittance(productId);
            Product product = ProductRepository.GetProductDetail(productId);
            product.ProductProps = ProductRepository.GetProductProps(productId);
            product.ProductRights = ProductRepository.GetProductRights(productId);
            ProductViewModel productview = CopyMethod.CopyProductModel(product);
            return PartialView("ProductDetail", productview);
        }

        public PartialViewResult NewProduct(string ProductId)
        {
            List<Product> listresult = ProductRepository.GetProductListForAddParent();
            ViewBag.ParentId = new SelectList(listresult, "ProductId", "ProductName",ProductId);
            ProductViewModel productview = new ProductViewModel();
            productview.ParentId = ProductId;
            productview.AuditOperation = "I";
            productview.TranAction = "I";
            productview.ProductProps = CopyMethod.CopyProductPropsModel(ProductRepository.GetProductProps(null));
            ViewBag.UserList = new SelectList(UserRepository.GetUserList(), "Sid", "UserName");
            return PartialView("ProductDetailEdit", productview);
        }

        public PartialViewResult EditProduct(string ProductId)
        {
           
            Product product = ProductRepository.GetProductDetail(ProductId);
            product.ProductProps = ProductRepository.GetProductProps(ProductId);
            product.ProductRights = ProductRepository.GetProductRights(ProductId);
            product.AuditOperation = "U";
            product.TranAction = "I";
            List<Product> listresult = ProductRepository.GetProductListForAddParent().Where(s =>s.ProductId != ProductId).ToList();
            ViewBag.ParentId = new SelectList(listresult, "ProductId", "ProductName", product.ParentId);
            ViewBag.ListUser = new SelectList(UserRepository.GetUserList(), "Sid", "UserName");
            ViewBag.ListGroup = new SelectList(GroupRepository.GetGroupList(), "Sid", "GroupName");
            ProductViewModel model = CopyMethod.CopyProductModel(product);
            return PartialView("ProductDetailEdit", model);
        }

        [ChildActionOnly]
        public PartialViewResult RenderSysRight(List<SysRight> models)
        {
            ViewBag.ListUser = new SelectList(UserRepository.GetUserList(), "Sid", "UserName");
            ViewBag.ListGroup = new SelectList(GroupRepository.GetGroupList(), "Sid", "GroupName");
            return PartialView("_EditACL", models);
        }


        [HttpPost]
        public JsonResult SaveProduct(ProductViewModel productview, string Sysright)
        {
            ValidateModel(productview);
            JavaScriptSerializer jsonconvert = new JavaScriptSerializer();
            List<SysRight> listright = jsonconvert.Deserialize<List<SysRight>>(Sysright);
            productview.ProductRights = listright;
            Mapper.CreateMap<ProductViewModel, Product>();
            Mapper.CreateMap<ProductPropsViewModel, ProductProps>();
            Product productmodel = Mapper.Map<ProductViewModel, Product>(productview);
            ProductRepository.SaveProduct(productmodel);
            return Json(productmodel);
        }

        [HttpPost]
        public EmptyResult DeleteProduct(string ProductId)
        {
            ProductRepository.DeleteProduct(ProductId);

            return new EmptyResult();
        }

        public ViewResult GetProductAudList()
        {

            return View("GridViewDevexpress");
        }

        public PartialViewResult getProductAudDetail(string productAudID)
        {
            Product model = ProductRepository.GetProductAudDetail(productAudID);
            model.ProductProps = ProductRepository.GetProductAudProps(productAudID);
            model.ProductRights = ProductRepository.GetProductAudRight(productAudID);
            return PartialView("ApprovalProductDetail", model);
        }

        public JsonResult Approve(string productAudID)
        {
            HttpStatusCode statuscode = ProductRepository.ApproveProduct(productAudID);
            return Json(statuscode, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Reject(string productAudID)
        {
            return Json("true", JsonRequestBehavior.AllowGet);
        }




        [ValidateInput(false)]
        public ActionResult GridViewPartial()
        {
            var model = ProductRepository.GetProductAudList();
            return PartialView("_GridViewPartial", model);
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult GridViewPartialAddNew([ModelBinder(typeof(DevExpressEditorsBinder))] los_controller.Models.ProductAudLite item)
        {
            var model = new object[0];
            if (ModelState.IsValid)
            {
                try
                {
                    // Insert here a code to insert the new item in your model
                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            }
            else
                ViewData["EditError"] = "Please, correct all errors.";
            return PartialView("_GridViewPartial", model);
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult GridViewPartialUpdate([ModelBinder(typeof(DevExpressEditorsBinder))] los_controller.Models.ProductAudLite item)
        {
            var model = new object[0];
            if (ModelState.IsValid)
            {
                try
                {
                    // Insert here a code to update the item in your model
                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            }
            else
                ViewData["EditError"] = "Please, correct all errors.";
            return PartialView("_GridViewPartial", model);
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult GridViewPartialDelete(System.String productAudId)
        {
            var model = new object[0];
            if (productAudId != null)
            {
                try
                {
                    // Insert here a code to delete the item from your model
                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            }
            return PartialView("_GridViewPartial", model);
        }
    }
}

los-controller/Views/Shared/_ButtonBar.cshtml
@model los_controller.Models.ButtonModel

@{
    if (Model.rightName.Contains(los_controller.Utility.EnumUtil.AclEnum.I.ToString()))
    {
        <span id="new-product" class="icon-plus border-left-1-1" title="New">New</span>
    }
    if (Model.rightName.Contains(los_controller.Utility.EnumUtil.AclEnum.U.ToString()))
    {
        <span id="edit-product" class="icon-note border-left-1-1" title="Edit">Edit</span>
    }
    if (Model.rightName.Contains(los_controller.Utility.EnumUtil.AclEnum.D.ToString()))
    {
        <span id="delete-product" class="icon-trash border-left-1-1" title="Delete">Delete</span>
    }
}

los-controller/Views/Shared/_EditACL.cshtml
@model   List<los_controller.Models.SysRight>
<div class="changeACL">
    <h4>Users:</h4>
    <div class="addUserItem background-1 border-top-bottom-1">
        <form name="formAddUser">
            <p>
                @Html.DropDownList("userAdd", (IEnumerable<SelectListItem>)ViewBag.ListUser)
            </p>
            <p class="multiple">
                <select name="quyenUser" multiple>
                    <option value="V">View</option>
                    <option value="I">Input</option>
                    <option value="U">Update</option>
                    <option value="D">Delete</option>
                    <option value="A">Approve</option>
                </select>
            </p>
            <span class="addUser border-1">Add</span>
        </form>
    </div>
    <ul class="listUser">
        @if (Model != null && Model.Count() > 0)
        {
            var UserRight = Model.Where(e => e.Type.Equals(los_controller.Utility.EnumUtil.RightEnum.User)).ToList();
            for (int i = 0; i < UserRight.Count; i++)
            {
                <li data-id="@UserRight[i].Sid" data-quyen="@UserRight[i].Acl" class="border-bottom-1-2">
                    <div class="nameUser"><a href="#" class="icon-user">@UserRight[i].Name</a></div>
                    <div class="quyenUser">

                        @if (@UserRight[i].Acl.Contains("V"))
                        {
                            <span data-quyen="V" class="border-1 applyQuyen">View</span>
                        }
                        else
                        {
                            <span data-quyen="V" class="border-1">View</span>
                        }
                        @if (@UserRight[i].Acl.Contains("I"))
                        {
                            <span data-quyen="I" class="border-1 applyQuyen">Input</span>
                        }
                        else
                        {
                            <span data-quyen="I" class="border-1">Input</span>
                        }
                        @if (@UserRight[i].Acl.Contains("U"))
                        {
                            <span data-quyen="U" class="border-1 applyQuyen">Update</span>
                        }
                        else
                        {
                            <span data-quyen="U" class="border-1">Update</span>
                        }
                        @if (@UserRight[i].Acl.Contains("D"))
                        {
                            <span data-quyen="D" class="border-1 applyQuyen">Delete</span>
                        }
                        else
                        {
                            <span data-right="D" class="border-1">Delete</span>
                        }
                        @if (@UserRight[i].Acl.Contains("X"))
                        {
                            <span data-quyen="X" class="border-1 applyQuyen">Execute</span>
                        }
                        else
                        {
                            <span data-right="X" class="border-1">Execute</span>
                        }
                        @if (@UserRight[i].Acl.Contains("A"))
                        {
                            <span data-quyen="A" class="border-1 applyQuyen">Approve</span>
                        }
                        else
                        {
                            <span data-quyen="A" class="border-1">Approve</span>
                        }
                    </div>
                    <div class="deleteUser"><span class="removeUser icon-close"></span></div>
                </li>
            }
        }

    </ul>

    <h4>Groups:</h4>
    <div class="addGroupItem background-1 border-top-bottom-1">
        <form name="formAddGroup">
            <p>
                @Html.DropDownList("selectGroup", (IEnumerable<SelectListItem>)ViewBag.ListGroup)
            </p>
            <p class="multiple">
                <select class="quyenGroup" name="quyenGroup" multiple>
                    <option value="V">View</option>
                    <option value="I">Input</option>
                    <option value="U">Update</option>
                    <option value="D">Delete</option>
                    <option value="A">Approve</option>
                </select>
            </p>
            <span class="addGroup border-1">Add</span>
        </form>
    </div>
    <ul class="listGroup">
        @if (Model != null && Model.Count() > 0)
        {
            var UserRight = Model.Where(e => e.Type.Equals(los_controller.Utility.EnumUtil.RightEnum.Group)).ToList();
            for (int i = 0; i < UserRight.Count; i++)
            {
                <li data-id="@UserRight[i].Sid" data-quyen="@UserRight[i].Acl" class=" border-bottom-1-2">
                    <div class="nameGroup"><a href="#" class="icon-users">@UserRight[i].Name</a></div>
                    <div class="quyenGroup">

                        @if (@UserRight[i].Acl.Contains("V"))
                        {
                            <span data-quyen="V" class="border-1 applyQuyen">View</span>
                        }
                        else
                        {
                            <span data-quyen="V" class="border-1">View</span>
                        }
                        @if (@UserRight[i].Acl.Contains("I"))
                        {
                            <span data-quyen="I" class="border-1 applyQuyen">Input</span>
                        }
                        else
                        {
                            <span data-quyen="I" class="border-1">Input</span>
                        }
                        @if (@UserRight[i].Acl.Contains("U"))
                        {
                            <span data-quyen="U" class="border-1 applyQuyen">Update</span>
                        }
                        else
                        {
                            <span data-quyen="U" class="border-1">Update</span>
                        }
                        @if (@UserRight[i].Acl.Contains("D"))
                        {
                            <span data-quyen="D" class="border-1 applyQuyen">Delete</span>
                        }
                        else
                        {
                            <span data-right="D" class="border-1">Delete</span>
                        }
                        @if (@UserRight[i].Acl.Contains("X"))
                        {
                            <span data-quyen="X" class="border-1 applyQuyen">Execute</span>
                        }
                        else
                        {
                            <span data-right="X" class="border-1">Execute</span>
                        }
                        @if (@UserRight[i].Acl.Contains("A"))
                        {
                            <span data-quyen="A" class="border-1 applyQuyen">Approve</span>
                        }
                        else
                        {
                            <span data-quyen="A" class="border-1">Approve</span>
                        }
                    </div>
                    <div class="deleteGroup"><span class="removeGroup icon-close"></span></div>
                </li>
            }
        }
    </ul>
</div><!-- end. .changeACL -->
<input type="hidden" name="Sysright" id="SysrightHidden" />
<script type="text/javascript">
    $(document).ready(function () {

        //$.get('User/GetUserList', function (data) {
        //    $.each(data, function (index, val) {
        //        $('#UserlistAcl')
        //        .append($("<option></option>")
        //        .attr("value", val.Sid)
        //        .text(val.UserName));
        //    });
            
        //});

        //$.get('Group/GetGroupList', function (data) {
        //    $.each(data, function (index, val) {
        //        $('#GrouplistAcl')
        //        .append($("<option></option>")
        //        .attr("value", val.Sid)
        //        .text(val.GroupName));
        //    });

        //});
        var Sidarr = [];
        $('.changeACL .listGroup > li').each(function (index, item) {

            var sysright = {
                Sid: ($(item).data('id')).toString(),
                Acl: $(item).data('quyen')
            };
            console.log(sysright);
            Sidarr.push(sysright);
        });
        $('.changeACL .listUser > li').each(function (index, item) {
            var sysright = {
                Sid: ($(item).data('id')).toString(),
                Acl: $(item).data('quyen')
            };
            Sidarr.push(sysright);
        });
        $('#SysrightHidden').val(JSON.stringify(Sidarr));
        console.log($('#SysrightHidden').val());
    });
</script>

los-controller/Views/Shared/_EditUdf.cshtml
@model List<los_controller.Models.ProductPropsViewModel>

@if (Model != null && Model.Count > 0)
{
    for (int i = 0; i < Model.Count; i++)
    {
        <li>
            <span>@Model[i].FieldName</span>
            <p>
                @if (Model[i].FieldType != "D")
                {
                    @Html.TextBoxFor(model => model[i].UdfValue)
                }
                else
                {
                    @Html.TextBoxFor(model => model[i].UdfValue, new { @name = "date" })      
                }
                @Html.ValidationMessageFor(model => model[i].UdfValue)
            </p>
            @Html.HiddenFor(model =>model[i].UdfId)
            @Html.HiddenFor(model => model[i].ValType)
            @Html.HiddenFor(model => model[i].MinVal)
            @Html.HiddenFor(model => model[i].MaxVal)
            @Html.HiddenFor(model => model[i].MinLength)
            @Html.HiddenFor(model => model[i].MaxLength)
        </li>
    }
}
else
{
    <li>
        No custom product property
    </li>
}

los-controller/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test</title>
    @Styles.Render("~/Style/Product")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/underscore")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    <!-- The DevExpress ASP.NET MVC Extensions' scripts -->
    @*@Html.DevExpress().GetScripts(
        new Script { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
        new Script { ExtensionSuite = ExtensionSuite.HtmlEditor },
        new Script { ExtensionSuite = ExtensionSuite.GridView },
        new Script { ExtensionSuite = ExtensionSuite.PivotGrid },
        new Script { ExtensionSuite = ExtensionSuite.Editors },
        new Script { ExtensionSuite = ExtensionSuite.Chart },
        new Script { ExtensionSuite = ExtensionSuite.Report },
        new Script { ExtensionSuite = ExtensionSuite.Scheduler },
        new Script { ExtensionSuite = ExtensionSuite.TreeList }
    )*@

    @Html.DevExpress().GetStyleSheets(
        new StyleSheet { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
        new StyleSheet { ExtensionSuite = ExtensionSuite.Editors },
        new StyleSheet { ExtensionSuite = ExtensionSuite.HtmlEditor },
        new StyleSheet { ExtensionSuite = ExtensionSuite.GridView },
        new StyleSheet { ExtensionSuite = ExtensionSuite.PivotGrid },
        new StyleSheet { ExtensionSuite = ExtensionSuite.Chart },
        new StyleSheet { ExtensionSuite = ExtensionSuite.Report },
        new StyleSheet { ExtensionSuite = ExtensionSuite.Scheduler },
        new StyleSheet { ExtensionSuite = ExtensionSuite.TreeList }
    )
    <script type="text/javascript">
        $(document).ajaxError(function (event, jqxhr, settings, thrownError) {
            if (jqxhr.responseJSON) {
                alert(jqxhr.responseJSON.ErrorCode + "\n\n\n\n" + jqxhr.responseJSON.ErrorMessage);
            }
        });
    </script>

</head>
<body>
    <header id="header" class="border-bottom-1-2 bg-header">
        <nav id="header-nav">
            <div id="Accout-Notification">
                <div id="historyWork">
                    <span class="icon-clock" title="history Work"></span>
                    <div class="dropdown-menu border-1 bg-box">
                        history Work
                    </div>
                </div>
                <div id="Notification">
                    <span class="icon-bell" title="Notification"></span>
                    <div class="dropdown-menu border-1 bg-box">
                        Notification
                    </div>
                </div>
                <div id="accout">
                    <span class="icons-settings">
                        <a href="#">@User.Identity.Name</a>
                    </span>
                    <div class="dropdown-menu-1 border-1 bg-box">
                        profile / Settings
                    </div>
                </div>
            </div>
        </nav>
    </header>

    <div id="menu" class="bg-menu border-right-1">
        <nav>
            <ul>
                <li><a href="@Url.Action("Index", "Product")">Product</a></li>
                <li><a href="@Url.Action("GetProductAudList", "Product")">Product Audit List</a></li>
                <li><a href="@Url.Action("Index", "CustomerCategory")">Customer Category</a></li>
            </ul>
        </nav>
    </div>
        @RenderBody()

    @Scripts.Render("~/Scripts/jlinq")
    @Scripts.Render("~/Script/Dropdown")
</body>
</html>

los-controller/Views/Shared/_LayoutSecurity.cshtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>


    <!-- General meta information -->
    <title>Login Form by Oussama Afellad</title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="robots" content="index, follow" />
    <meta charset="utf-8" />
    <!-- // General meta information -->
    <!-- Load Javascript -->
    @Scripts.Render("~/bundles/jquerylogin")
    <!-- // Load Javascipt -->
    <!-- Load stylesheets -->
    <link type="text/css" rel="stylesheet" href="@Url.Content("~/Content/stylelogin.css")" media="screen" />
    <!-- // Load stylesheets -->

    <script>


        $(document).ready(function () {

            $("#submit1").hover(
            function () {
                $(this).animate({ "opacity": "0" }, "slow");
            },
            function () {
                $(this).animate({ "opacity": "1" }, "slow");
            });
        });


    </script>

</head>
<body>

    <div id="wrapper">
        <div id="wrappertop"></div>

        @RenderBody()

        <div id="wrapperbottom"></div>

        <div id="powered">
            <p>Powered by <a href="http://www.premiumfreebies.eu">Premiumfreebies Control Panel</a></p>
        </div>
    </div>

</body>
</html>

los-controller/Views/Shared/_ViewACL.cshtml
@model List<los_controller.Models.SysRight>

@helper CutACL(string acl)
{
    if (acl.Contains(los_controller.Utility.EnumUtil.AclEnum.V.ToString()))
    {
        <span class="border-1 applyQuyen">@los_controller.Resources.ACL.V</span>
        //edit
    }
    else
    {
        <span class="border-1">@los_controller.Resources.ACL.V</span>
    }
    if (acl.Contains(los_controller.Utility.EnumUtil.AclEnum.U.ToString()))
    {
        <span class="border-1 applyQuyen">@los_controller.Resources.ACL.U</span>
    }
    else
    {
        <span class="border-1">@los_controller.Resources.ACL.U</span>
    }
    if (acl.Contains(los_controller.Utility.EnumUtil.AclEnum.D.ToString()))
    {
        <span class="border-1 applyQuyen">@los_controller.Resources.ACL.D</span>
    }
    else
    {
        <span class="border-1">@los_controller.Resources.ACL.D</span>
    }
    if (acl.Contains(los_controller.Utility.EnumUtil.AclEnum.S.ToString()))
    {
        <span class="border-1 applyQuyen">@los_controller.Resources.ACL.S</span>
    }
    else
    {
        <span class="border-1">@los_controller.Resources.ACL.D</span>
    }
    if (acl.Contains(los_controller.Utility.EnumUtil.AclEnum.X.ToString()))
    {
        <span class="border-1 applyQuyen">@los_controller.Resources.ACL.X</span>
    }
    else
    {
        <span class="border-1">@los_controller.Resources.ACL.X</span>
    }
    if (acl.Contains(los_controller.Utility.EnumUtil.AclEnum.A.ToString()))
    {
        <span class="border-1 applyQuyen">@los_controller.Resources.ACL.A</span>
    }
    else
    {
        <span class="border-1">@los_controller.Resources.ACL.A</span>
    }

}

@if (Model != null && Model.Count > 0)
{
    if (Model.Count(e => e.Type == los_controller.Utility.EnumUtil.RightEnum.User) != 0)
    {
        <h4>Users:</h4>
        <ul class="listUser">
            @foreach (var datamodel in Model.Where(e => e.Type == los_controller.Utility.EnumUtil.RightEnum.User))
            {
                <li data-id=@datamodel.Sid class="border-bottom-1-2 border-top-1-2">

                    <div class="nameUser"><a href="#" class="icon-user">@datamodel.Name</a></div>
                    <div class="quyenUser">@CutACL(@datamodel.Acl)</div>
                </li>
            }
        </ul>
    }

    if (Model.Count(e => e.Type == los_controller.Utility.EnumUtil.RightEnum.Group) != 0)
    {
        <h4>Groups:</h4>
        <ul class="listGroup">
            @foreach (var datamodel in Model.Where(e => e.Type == los_controller.Utility.EnumUtil.RightEnum.Group))
            {
                <li data-id="@datamodel.Sid" class="border-bottom-1-2 border-top-1-2">
                    <div class="nameGroup"><a href="#" class="icon-users">@datamodel.Name</a></div>
                    <div class="quyenGroup">@CutACL(@datamodel.Acl)</div>
                </li>
            }
        </ul>
    }
}